SConscript('ch06-01-removal/SConscript', variant_dir='build-scons/ch06-01-removal', duplicate=0)
SConscript('ch06-02-fountain/SConscript', variant_dir='build-scons/ch06-02-fountain', duplicate=0)
SConscript('ch06-03-ship-sim-2/SConscript', variant_dir='build-scons/ch06-03-ship-sim-2', duplicate=0)
SConscript('ch06-04-bouncing-1/SConscript', variant_dir='build-scons/ch06-04-bouncing-1', duplicate=0)
SConscript('ch06-05-bouncing-2/SConscript', variant_dir='build-scons/ch06-05-bouncing-2', duplicate=0)
SConscript('ch06-06-friction-1/SConscript', variant_dir='build-scons/ch06-06-friction-1', duplicate=0)
SConscript('ch06-07-friction-2/SConscript', variant_dir='build-scons/ch06-07-friction-2', duplicate=0)
SConscript('ch06-08-ship-sim-friction/SConscript', variant_dir='build-scons/ch06-08-ship-sim-friction', duplicate=0)
