SConscript('ch07-01-mouse-events/SConscript', variant_dir='build-scons/ch07-01-mouse-events', duplicate=0)
SConscript('ch07-03-mouse-move-drag/SConscript', variant_dir='build-scons/ch07-03-mouse-move-drag', duplicate=0)
SConscript('ch07-04-drag-and-move-1/SConscript', variant_dir='build-scons/ch07-04-drag-and-move-1', duplicate=0)
SConscript('ch07-05-drag-and-move-2/SConscript', variant_dir='build-scons/ch07-05-drag-and-move-2', duplicate=0)
SConscript('ch07-06-throwing/SConscript', variant_dir='build-scons/ch07-06-throwing', duplicate=0)
