import os

env = Environment()

if env['PLATFORM'] == 'darwin':
    env['CXX'] = 'clang++'
    env['CCFLAGS'] = '-stdlib=libc++ '
    env['LINKFLAGS'] = '-stdlib=libc++ '  
elif env['PLATFORM'] == 'posix':
    env['CXX'] = 'g++'

    env.Append(LIBPATH=['/usr/lib/x86_64-linux-gnu/','#/ch04-12-video-frames/external-libraries/sfeMovie/lib/'])
    #add the path for using library after building
    env.Append(RPATH=['/usr/lib/x86_64-linux-gnu/','ch04-12-video-frames/external-libraries/sfeMovie/lib/'])

if env['PLATFORM'] == 'darwin':
    #not correct for darwin platform
    env.Append(CCFLAGS='-std=c++0x -g3 -Wall -Wextra -I/usr/include/ -I/usr/SFML/include/ -Ich04-12-video-frames/external-libraries/sfeMovie/include/')
elif env['PLATFORM'] == 'posix':    
    env.Append(CCFLAGS='-std=c++14 -g3 -Wall -Wextra -I/usr/include/ -I/usr/SFML/include/ -Ich04-12-video-frames/external-libraries/sfeMovie/include/')
    env.Append(LIBS=['sfml-system', 'sfml-window', 'sfml-graphics', 'sfeMovie'])
    env.Decider('content')

    env.Append(LIBPATH=['/usr/lib/x86_64-linux-gnu/','#/external-libraries/TGUI/lib/'])
    #add the path for using library after building
    env.Append(RPATH=['/usr/lib/x86_64-linux-gnu/','external-libraries/TGUI/lib/'])

if env['PLATFORM'] == 'darwin':
    #not correct for darwin platform
    env.Append(CCFLAGS='-std=c++0x -g3 -Wall -Wextra -I/usr/include/ -I/usr/SFML/include/ -Iexternal-libraries/TGUI/include/')
elif env['PLATFORM'] == 'posix':    
    env.Append(CCFLAGS='-std=c++0x -g3 -Wall -Wextra -I/usr/include/ -I/usr/SFML/include/ -Iexternal-libraries/TGUI/include/')
    env.Append(LIBS=['sfml-system', 'sfml-window', 'sfml-graphics','sfeMovie'])
    env.Decider('content')

src_files = Glob("Source/ch04-12-video-frames/*.cpp")
src_files += Glob("Source/ch04-12-video-frames/*/*.cpp")

objects=env.Object(source=src_files)

def DefineProgram(name, main):
    target = env.Program(name, source = objects , CPPPATH = '.') #
    env.Alias(name, target)
    run = env.Command(name+".out",[],"./build/"+name, ENV = os.environ)
    env.Alias(name+"-run", run)
    env.Depends(run, target)
    env.AlwaysBuild(run)
    env.Default(target)

DefineProgram('bin/ch04-12-video-frames', ['./src/main.cpp'])

